Первое ревью
Bo4oN/java-shareit pull request #2
Opened 2023-11-23 05:58 UTC by Bo4oN

2023-11-23 07:05 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/booking/dto/BookingOut.java
> +public class BookingOut {
Название Out не информативное, лучше заменить на Result или Response

2023-11-23 07:05 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +@AllArgsConstructor
Для создания бронирования весь перечень атрибутов избыточен, достаточно трех.

2023-11-23 07:09 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        switch (status) {
Нужно сделать тип перечислимое и использовать его вместо строк

2023-11-23 07:18 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +    @Query("select b from Booking as b " +
С запросами перемудрил, можно просто List<Booking> findByBooker_Id(Long bookerId, Sort sort);
или простыми селестами select * from Booking where booker = ?1 order by start desc
 
Вложенные селекты лишние

2023-11-23 07:19 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/exceptions/ErrorHandler.java
>  }
Нужно добавить перехват Throwable в 500ый статус

2023-11-23 07:21 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/item/model/Comment.java
> +    @Column(name = "item_id")
Нужно связать с объектам Item и User, а не их идентификаторами

2023-11-23 07:22 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    @Column(name = "owner_id")
@ManyToOne(optional = false)
	@JoinColumn(name = "owner_id", nullable = false)
	private User owner;

2023-11-23 07:23 UTC, VadimZharkov requested changes
Нужно исправить замечания

2023-11-23 11:24 UTC, Bo4oN commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +@AllArgsConstructor
У меня этот класс в некоторых сценариях возвращается

2023-11-24 06:25 UTC, VadimZharkov approved these changes

2023-11-24 07:34 UTC, merged